---
- name: Set docker and k3s variables from environment
  set_fact:
    docker_path: "{{ lookup('env', 'DOCKER_PATH') | default('/data/orin/docker', true) }}"
    ethernet:
      ip: "{{ lookup('env', 'JETSON_ETH_IP') | default('192.168.50.10/24', true) }}"
      gateway: "{{ lookup('env', 'JETSON_ETH_GATEWAY') | default('192.168.50.1', true) }}"
      dns: "{{ lookup('env', 'JETSON_ETH_DNS') | default('192.168.50.1', true) }}"
      interface: "{{ lookup('env', 'JETSON_ETH_INTERFACE') | default('enP8p1s0', true) }}"
      name: "{{ lookup('env', 'JETSON_ETH_NAME') | default('JetsonEthernet', true) }}"
  tags: always

- name: Créer le dossier K3s
  file:
    path: "{{ docker_path}}"
    state: directory
    mode: '0755'
  become: yes

- name: Configure Docker daemon for external storage
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "data-root": "{{ docker_path}}",
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m",
          "max-file": "3"
        }        
      }
    owner: root
    group: root
    mode: '0644'
  tags: docker

# --------------------------------------------------
# 4. Override systemd pour Docker
# --------------------------------------------------
- name: Create docker systemd override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Ensure Docker waits for mounted disk
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Unit]
      After=network-online.target
      Wants=network-online.target

# --------------------------------------------------
# 5. Activer Docker au boot
# --------------------------------------------------
- name: Ensure Docker is enabled
  service:
    name: docker
    enabled: true
    state: started


- name: Configure NVIDIA runtime for Docker
  command: nvidia-ctk runtime configure --runtime=docker --set-as-default
  become: true

- name: Ajouter options cgroup à la fin de la ligne APPEND
  lineinfile:
    path: /boot/extlinux/extlinux.conf
    regexp: '^(\s*APPEND.*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: yes

- name: Reboot si nécessaire
  reboot:
    msg: "Reboot après modification"
    reboot_timeout: 600

- name: Vérifier que la machine est revenue
  command: uptime

- name: Disable swap (required by k3s)
  command: swapoff -a
  when: ansible_facts['swaptotal_mb'] > 0
  tags: prepare

# Il faut absolument une IP réseau pour que K3s puisse fonctionner
- name: Check if connection exists
  command: nmcli -t -f NAME connection show
  register: nmcli_connections
  changed_when: false

- name: Create ethernet connection if not exists
  command: >
    nmcli connection add
    type ethernet
    ifname {{ ethernet.interface }}
    con-name {{ ethernet.name }}
    autoconnect yes
  when: ethernet.name not in nmcli_connections.stdout

- name: Configure ethernet static IP
  command: >
    nmcli connection modify {{ ethernet.name }}
    ipv4.method manual
    ipv4.addresses {{ ethernet.ip }}
    ipv4.gateway {{ ethernet.gateway }}
    ipv4.dns "{{ ethernet.dns }}"
    ipv6.method ignore
    connection.autoconnect-priority 999

- name: Create systemd service file
  copy:
    dest: /etc/systemd/system/jetson-eth.service
    content: |
      [Unit]
      Description=Force Ethernet connection up
      After=NetworkManager.service network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/nmcli connection up {{ ethernet.name }}
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

- name: Create systemd override directory for k3s
  file:
    path: /etc/systemd/system/k3s.service.d
    state: directory

- name: Configure k3s to wait for network and ethernet
  copy:
    dest: /etc/systemd/system/k3s.service.d/override.conf
    content: |
      [Unit]
      After=network-online.target jetson-eth.service
      Wants=network-online.target
      Requires=jetson-eth.service          

- name: Reload systemd
  command: systemctl daemon-reexec

- name: Enable service
  command: systemctl enable jetson-eth.service

- name: Créer le dossier K3s pour la config rancher
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'
  become: yes

- name: Créer le dossier de stockage K3s
  file:
    path: /data/orin/k3s
    state: directory
    mode: '0755'
  become: yes

- name: Configurer K3s pour Jetson
  copy:
    dest: /etc/rancher/k3s/config.yaml
    mode: '0644'
    content: |
      # K3s server configuration for NVIDIA Jetson
      token: "JetsonClusterToken"
      
      node-ip: {{ ethernet.ip.split('/')[0] }}
      advertise-address: {{ ethernet.ip.split('/')[0] }}
      flannel-iface: {{ ethernet.interface }}

      #tls-san:
      #  - $(hostname -I | awk '{print $1}')
      #  - $(hostname)

      # Kubelet configuration for Jetson
      kubelet-arg:
        - "max-pods=110"
        - "kube-reserved=cpu=500m,memory=1Gi"
        - "system-reserved=cpu=500m,memory=512Mi"
        - "eviction-hard=memory.available<200Mi,nodefs.available<5%"

      # Node labels for GPU workload targeting
      node-label:
        - "device-type=jetson"
        - "accelerator=nvidia-gpu"
        - "nvidia.com/gpu=true"

# Docker doit absolument être lancé avant k3s
- name: Create systemd override directory for k3s
  file:
    path: /etc/systemd/system/k3s.service.d
    state: directory
    mode: '0755'

- name: Add override to make k3s depend on Docker
  copy:
    dest: /etc/systemd/system/k3s.service.d/override.conf
    content: |
      [Unit]
      After=docker.service
      Requires=docker.service

- name: Install K3s
  shell: |
    curl -sfL https://get.k3s.io | sudo sh -s - --docker --data-dir=/data/orin/k3s --write-kubeconfig-mode=644 --disable traefik --disable servicelb
  args:
    creates: /usr/local/bin/k3s
    executable: /bin/bash
  tags: k3s

- name: Wait for K3s node ready
  shell: |
    k3s kubectl get node
  register: result
  retries: 10
  delay: 10
  until: result.rc == 0
  tags: k3s

# --------------/-----------
# INSTALL NVIDIA DEVICE PLUGIN
# -------------------------

- name: Deploy NVIDIA device plugin
  shell: |
    k3s kubectl apply -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.1/nvidia-device-plugin.yml
  args:
    creates: /tmp/nvidia-device-plugin-installed
  tags: nvidia

- name: Mark plugin installed
  file:
    path: /tmp/nvidia-device-plugin-installed
    state: touch
  tags: nvidia

  