---
- name: Set deployment variables from environment
  set_fact:
    app_namespace: "{{ lookup('env', 'APP_NAMESPACE') | default('countingapp-dev', true) }}"
    app_name: "{{ lookup('env', 'APP_NAME') | default('countingapp', true) }}"
    app_version: "{{ lookup('env', 'APP_VERSION') | default('local', true) }}"
    app_port: "{{ lookup('env', 'APP_PORT') | default('31501', true) }}"
    video_device: "{{ lookup('env', 'VIDEO_DEVICE') | default('/dev/video0', true) }}"
    app_path: "{{ lookup('env', 'APP_PATH') | default('/data/orin/git/animal-counting/app', true) }}"
    files_path: "{{ lookup('env', 'FILES_PATH') | default('/data/orin/files', true) }}"
    max_log_files: "{{ lookup('env', 'MAX_LOG_FILES') | default('50', true) }}"
    log_max_size: "{{ lookup('env', 'LOG_MAX_SIZE') | default('100M', true) }}"
    jetson_ip_wifi: "{{ lookup('env','JETSON_IP') }}"
    k3s_app: "{{ lookup('env', 'K3S_APP_PATH') | default('/data/orin/git/animal-counting/k3s', true) }}"
    # FileBrowser configuration
    filebrowser_port: "{{ lookup('env', 'FILEBROWSER_PORT') | default('80', true) }}"
    filebrowser_base_url: "{{ lookup('env', 'FILEBROWSER_BASE_URL') | default('/', true) }}"
    filebrowser_cache_dir: "{{ lookup('env', 'FILEBROWSER_CACHE_DIR') | default('/data/tmp', true) }}"
    filebrowser_database: "{{ lookup('env', 'FILEBROWSER_DATABASE') | default('/data/database.db', true) }}"
    filebrowser_srv_path: "{{ lookup('env', 'FILEBROWSER_SRV_PATH') | default('/srv', true) }}"
    filebrowser_admin_username: "{{ lookup('env', 'FILEBROWSER_ADMIN_USERNAME') | default('admin', true) }}"
    filebrowser_admin_password: "{{ lookup('env', 'FILEBROWSER_ADMIN_PASSWORD') | default('admin', true) }}"
    filebrowser_image: "{{ lookup('env', 'FILEBROWSER_IMAGE') | default('ghcr.io/gtsteffaniak/filebrowser:stable', true) }}"
    filebrowser_config_path: "{{ lookup('env', 'FILEBROWSER_CONFIG_PATH') | default('/data/orin/git/animal-counting/config/filebrowser/', true) }}"
  tags: always

- name: Pull Docker image
  community.docker.docker_image:
    name: lscr.io/linuxserver/ffmpeg
    tag: latest
    source: pull
    
- name: Create files directory on Jetson
  file:
    path: "{{ files_path }}"
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
  tags: always

- name: Create dataset directory on Jetson
  file:
    path: "{{ files_path }}/dataset"
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
  tags: always

- name: Create k3s directory on Jetson
  file:
    path: "{{ k3s_app }}"
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
  tags: always

- name: Create config files filebrowser directory on Jetson
  file:
    path: "{{ filebrowser_config_path }}"
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
  tags: always

- name: Render namespace template
  template:
    src: ../../../k3s/templates/countingapp-ns.j2
    dest: "{{ k3s_app }}/countingapp-ns.yaml"
  become: yes
  tags: namespace

- name: Render counting app test
  template:
    src: "../../../k3s/templates/countingapp-test.j2"
    dest: "{{ app_path }}/../k3s/countingapp-test.yaml"
  become: yes

- name: Render countingapp deployment template
  template:
    src: ../../../k3s/templates/countingapp-dep.j2
    dest: "{{ k3s_app }}/countingapp-dep.yaml"
  become: yes
  tags: deployment

- name: Render countingapp service template
  template:
    src: ../../../k3s/templates/countingapp-svc.j2
    dest: "{{ k3s_app }}/countingapp-svc.yaml"
  become: yes
  tags: service

- name: Render filebrowser configmap template
  template:
    src: ../../../k3s/templates/filebrowser-cmap.j2
    dest: "{{ k3s_app }}/filebrowser-cmap.yaml"
  become: yes
  tags: filebrowser

- name: Render filebrowser deployment template
  template:
    src: ../../../k3s/templates/filebrowser-dep.j2
    dest: "{{ k3s_app }}/filebrowser-dep.yaml"
  become: yes
  tags: filebrowser

- name: Render filebrowser secret template
  template:
    src: ../../../k3s/templates/filebrowser-sct.j2
    dest: "{{ k3s_app }}/filebrowser-sct.yaml"
  become: yes
  tags: filebrowser

- name: Render cronvideo template
  template:
    src: ../../../k3s/templates/cronvideo-dep.j2
    dest: "{{ k3s_app }}/cronvideo-dep.yaml"
  become: yes
  tags: cleanup

# Nécessaire pour autoriser x11 via k3s
- name: Create xauth file
  file:
    path: "{{ k3s_app }}/.k3s.xauth"
    state: touch
    mode: '0644'

- name: Generate xauth content
  shell: |
    xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f {{ k3s_app }}/.k3s.xauth nmerge -

- name: Apply namespace using kubectl
  command: >
    k3s kubectl apply -f {{ k3s_app }}/countingapp-ns.yaml
  become: yes
  tags: namespace

# - name: Deploy counting app test (test)
#   ansible.builtin.command: >
#     kubectl apply -f {{ app_path }}/../k3s/countingapp-test.yaml
#   become: yes

- name: Deploy countingapp deployment using kubectl
  command: >
    k3s kubectl apply -f {{ k3s_app }}/countingapp-dep.yaml
  become: yes
  tags: deployment

- name: Deploy countingapp service using kubectl
  command: >
    k3s kubectl apply -f {{ k3s_app }}/countingapp-svc.yaml
  become: yes
  tags: service

- name: Deploy filebrowser configmap using kubectl
  command: >
    k3s kubectl apply -f {{ k3s_app }}/filebrowser-cmap.yaml
  become: yes
  tags: filebrowser

- name: Deploy filebrowser secret using kubectl
  command: >
    k3s kubectl apply -f {{ k3s_app }}/filebrowser-sct.yaml
  become: yes
  tags: filebrowser

- name: Deploy filebrowser deployment using kubectl
  command: >
    k3s kubectl apply -f {{ k3s_app }}/filebrowser-dep.yaml
  become: yes
  tags: filebrowser

- name: Deploy video compress cronjob using kubectl
  command: >
    k3s kubectl apply -f {{ k3s_app }}/cronvideo-dep.yaml
  become: yes
  tags: compress

# - name: Configure log rotation
#   copy:
#     dest: /etc/logrotate.d/k3s-countingapp
#     content: |
#       {{ files_path }}/*.log {
#         daily
#         rotate {{ max_log_files }}
#         size {{ log_max_size }}
#         compress
#         delaycompress
#         missingok
#         notifempty
#         create 0644 root root
#       }
#   tags: logs

# - name: Setup log rotation cron
#   cron:
#     name: "Rotate countingapp logs"
#     minute: "0"
#     hour: "2"
#     job: "/usr/sbin/logrotate -f /etc/logrotate.d/k3s-countingapp"
#   tags: logs