events { }

http {

  server {
    listen 80;

    location / {
      proxy_pass http://filebrowser:31500/;
    }

    location /flask {
      proxy_pass http://countingapp:31501/;
    }
  }
}
