apiVersion: v1	
kind: Service
metadata:
  labels:
    app: countingapp
  name: countingapp
  namespace: countingapp-dev
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 31501
    protocol: TCP
    targetPort: web
  selector:
    app: countingapp
  externalIPs:
    - "192.168.1.158"

#  type: LoadBalancer
