apiVersion: v1
kind: Service
metadata:
  namespace: countingapp-dev
  labels:
    app: filebrowser
  name: filebrowser
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: filebrowser
  externalIPs:
    - "192.168.0.243"
