apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-scripts
  namespace: countingapp-dev
  labels:
    app: filebrowser
data:
  init-filebrowser.sh: |
    #!/usr/bin/env sh

    /filebrowser config init
    /filebrowser config set \
        --port 80 \
        --address 0.0.0.0 \
        --baseurl "/" \
        --root "/srv" \
        --branding.name "hi, welcome." \
        --branding.disableExternal
    /filebrowser users add guest guest --perm.admin
    exec /filebrowser --port 80 --disable-exec
