apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: countingapp-dev
spec:
  selector:
    matchLabels:
      app: filebrowser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: filebrowser
            mountPath: /srv
            #subPath: files
          - name: filebrowser-db
            mountPath: /database.db
            #subPath: database.db
          - name: filebrowser-scripts
            mountPath: /scripts
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "512m"
        command: ["/bin/sh", "-c", "/scripts/init-filebrowser.sh"]
      volumes:
        - name: filebrowser
          hostPath:
            path: /data/orin/files
            type: Directory     
        - name: filebrowser-scripts
          configMap:
            name: filebrowser-scripts
            defaultMode: 0755   
        - name: filebrowser-db
          hostPath:
            path: /data/orin/repository/git/animal-counting/config/filebrowser/
            type: Directory
