apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-svc
  namespace: countingapp-dev
spec:
  selector:
    app: reverse-proxy-depl
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  externalIPs:
    - "192.168.1.158"
