apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: countingapp-dev
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:local
        ports:
        - containerPort: 6379
      restartPolicy: Always
